GPT4_VISION_KEY: "vision key"
GPT4_VISION_API_VERSION: Version of the API
GPT4_VISION_DEPLOYMENT_NAME: gpt-4- vision deployment name
GPT4_VISION_BASE: gpt4 vision base name
GPT4_VISION_MAX_TOKENS: 4096
GPT4_VISION_BATCH_CONCURRENCY: 2